# All the CI config is in the library-utils area of the
# kicad-library-tools repo
#
# The goal is to have only one place where all the CI
# related things are.
include:
  - remote: 'https://gitlab.com/kicad/libraries/kicad-library-tools/-/raw/main/.gitlab-ci-symbols.yml'
